name: Run .NET Console App Once

on:
  schedule:
    - cron: '15 * * * *'
  workflow_dispatch:  # Allows you to trigger it manually

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Run the console app
      working-directory: ./TradingBot
      run: dotnet run --configuration Release
